### ISSUE TITLE
Haswell mrc.bin how clean is it ?

### ISSUE THREAD

**Issue by intika** [mytbk/r2dumpbin#1]
First thanks for sharing your work :) 

I am interested as well in reversing this binary but i have limited time for the task :(... i had a look at what you did in your coreboot fork, nice work!

On that same tree, i saw that some parts was not really translated but nice effort :) 

As you dig a little bit on that binary i would like to ask you for your point of view on its cleanness, what i mean is, regarding what you had been able to decode do you think its content is clean from anything that could violate the privacy? From your perspective do you think that code could do more than what's claimed by Intel? 

Thanks ;)

**Comment by mytbk** [comment]
I don't know. I've just reverse engineered the UEFI PEI implementation in mrc.bin, USB init, very little part of DRAM handling, so I have no idea what other code does.
In 2019, I was working at my graduate thesis until July, and I'm now working for some company, so I have little time at the moment.
The good news is we now have a free good decompiler in Ghidra, and we can make use of it. In the past, the tool I used was radare2 and the r2dec plugin, and manually translate the C code from assembly myself.

**Comment by intika** [comment]
Cool thanks for the feedback :) ... 

I just tried it on Ghidra, well it's very nice but as you expect it's not revolutionary reversing c code is not an easy task. at least it is useful to have everything in one gui... 

if only we could reverse some text, functions names etc...

**Comment by intika** [comment]
here is what it look like 
[file.h.txt](https://github.com/mytbk/r2dumpbin/files/3778092/file.h.txt)
[file.c.txt](https://github.com/mytbk/r2dumpbin/files/3778095/file.c.txt)

**Comment by mytbk** [comment]
BTW, if you want to use my coreboot fork, please use the haswell-dumpbin-rework branch, it fixes some error in the previous haswell-dumpbin branch.

**Comment by intika** [comment]
> BTW, if you want to use my coreboot fork, please use the haswell-dumpbin-rework branch, it fixes some error in the previous haswell-dumpbin branch.

Great thanks... i'll let you know if anything happen on my side...

**Comment by mytbk** [comment]
I've rebased and moved the code to the haswell-dumpbin branch again, and use ghidra to decompile some functions. The code works good on my T440p.

**Comment by intika** [comment]
> I've rebased and moved the code to the haswell-dumpbin branch again, and use ghidra to decompile some functions. The code works good on my T440p.

Cool :) i'll test/update that next month on my chromebook thank you for the update
